#!/bin/bash -l
#PBS -A stf007
#PBS -q batch
#PBS -l walltime=01:00:00
#PBS -o util_baseline.$PBS_JOBID.out.log
#PBS -N util_baseline
#PBS -j oe

PPN=16

echo 'Testing resources used by backgrounded aprun calls.'
echo "Host: $HOST"
echo "Nodes: $PBS_NUM_NODES"
echo "PPN: $PPN"

module unload wraprun

RUNDIR=$PROJWORK/stf007/belhorn/wraprun/
cd $RUNDIR

PROG=./a.out

for i in `seq 1 $PBS_NUM_NODES`; do
  aprun -n $PPN -N $PPN $PROG &
done

sleep 30

PSLOG=$RUNDIR/util_wraprun.$PBS_JOBID.log
printf "Aprun resource usage log.\n\n" >> $PSLOG
PROCS=`ps -U $USER -o comm,pid,c,size,rss | grep -e '^\(COMMAND\|aprun\)'`
echo "$PROCS" >> $PSLOG
printf "\n\nMemory Summary\n==============\nSIZE  RSS\n" >> $PSLOG
echo "$PROCS" | grep -e '^aprun\s' |  awk '{size += $4; rss += $5} END {print size, rss}' >> $PSLOG

wait

mv $PSLOG $PBS_O_WORKDIR/util_baseline.o$PBS_JOBID.mem.log
