#!/bin/bash -l
#PBS -A stf007
#PBS -q batch
#PBS -l walltime=00:05:00
#PBS -N wraprun_util_baseline
#PBS -o util_baseline.pbs.log
#PBS -j oe

echo 'Testing resources used by backgrounded aprun calls.'

module unload wraprun

RUNDIR=$PROJWORK/stf007/belhorn/wraprun/
cd $RUNDIR

PROG=./a.out

for i in `seq 1 $PBS_NUM_NODES`; do
  aprun -n 16 -N 16 $PROG &
done

sleep 30

PSLOG=$RUNDIR/util_wraprun.$PBS_JOBID.log
printf "Aprun resource usage log.\n\n" >> $PSLOG
PROCS=`ps -U $USER -o comm,pid,c,size,rss | grep -e '^\(COMMAND\|aprun\)'`
echo "$PROCS" >> $PSLOG
printf "\n\nMemory Summary\n==============\nSIZE  RSS\n" >> $PSLOG
echo "$PROCS" | grep -e '^aprun\s' |  awk '{size += $4; rss += $5} END {print size, rss}' >> $PSLOG

wait

mv $PSLOG $PBS_O_WORKDIR/util_baseline.ps.log
