#!/bin/bash -l
#PBS -A stf007
#PBS -q batch
#PBS -l walltime=01:00:00
#PBS -N util_single
#PBS -j oe

PPN=16

echo "Testing resources used by a single SPSD aprun call."
echo "Host: $HOST"
echo "Nodes: $PBS_NUM_NODES"
echo "PPN: $PPN"

module unload wraprun

RUNDIR=$PROJWORK/stf007/belhorn/wraprun/
cd $RUNDIR

PROG=./a.out

PES=$(($PBS_NUM_NODES * $PPN))

aprun -n $PES -N $PPN $PROG &

sleep 30

PSLOG=$RUNDIR/util_wraprun.$PBS_JOBID.log
printf "Aprun resource usage log.\n\n" >> $PSLOG
PROCS=`ps -U $USER -o comm,pid,c,size,rss | grep -e '^\(COMMAND\|aprun\)'`
echo "$PROCS" >> $PSLOG
printf "\n\nMemory Summary\n==============\nSIZE  RSS\n" >> $PSLOG
echo "$PROCS" | grep -e '^aprun\s' |  awk '{size += $4; rss += $5} END {print size, rss}' >> $PSLOG

wait

mv $PSLOG $PBS_O_WORKDIR/util_single.o$PBS_JOBID.mem.log

