#!/bin/bash -l
#PBS -A stf007
#PBS -q batch
#PBS -l walltime=01:00:00
#PBS -o util_wraprun.$PBS_JOBID.out.log
#PBS -N util_wraprun
#PBS -j oe

PPN=16

echo 'Testing resources used by wraprun MPMD calls.'
echo "Host: $HOST"
echo "Nodes: $PBS_NUM_NODES"
echo "PPN: $PPN"

module load wraprun/dev

RUNDIR=$PROJWORK/stf007/belhorn/wraprun/
cd $RUNDIR

PROG=./a.out

cmd="wraprun --w-debug -b "
arg="-n $PPN -N $PPN $PROG"
sep=" : "
for i in `seq 1 $(($PBS_NUM_NODES-1))`; do
  cmd+=$arg
  cmd+=$sep
done
cmd+=$arg

eval $cmd &

sleep 30

PSLOG=$RUNDIR/util_wraprun.$PBS_JOBID.log
printf "Aprun resource usage log.\n\n" >> $PSLOG
PROCS=`ps -U $USER -o comm,pid,c,size,rss | grep -e '^\(COMMAND\|aprun\)'`
echo "$PROCS" >> $PSLOG
printf "\n\nMemory Summary\n==============\nSIZE  RSS\n" >> $PSLOG
echo "$PROCS" | grep -e '^aprun\s' |  awk '{size += $4; rss += $5} END {print size, rss}' >> $PSLOG

wait

mv $PSLOG $PBS_O_WORKDIR/util_wraprun.$PBS_JOBID.mem.log
